### ISSUE TITLE
Is it possible to run julia test with multiple threads?

### ISSUE THREAD

**Issue by TheStarAlight** [julia-actions/julia-runtest#141]
Hi, I'm using the julia-runtest action in my repo, I would like to run the test with two threads. I tried:
```
- uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
          test_args: '-t 2'
```
but this didn't work. How can I achieve this?
