### ISSUE TITLE
Having trouble disabling depwarns.

### ISSUE THREAD

**Issue by ablaom** [julia-actions/julia-runtest#49]
I have made [this change](https://github.com/FluxML/MLJFlux.jl/pull/181/commits/048be5d3408610194177eef17b3801e45f29ee6d) to my ci.yml but it does not appear to have disabled dep warnings. Am I missing something here?

Here's the fail (due to depwarns) : https://github.com/FluxML/MLJFlux.jl/pull/181/checks?check_run_id=3100578201

**Comment by korsbo** [comment]
would not 
https://github.com/julia-actions/julia-runtest/blob/7ea3b3e0bd2f7de6d8104e238f69a715c988a5d1/test_harness.jl#L5

which feeds into 
https://github.com/julia-actions/julia-runtest/blob/7ea3b3e0bd2f7de6d8104e238f69a715c988a5d1/test_harness.jl#L15

ignore the depwarn flag?

**Comment by korsbo** [comment]
Strange

I can't seem to turn off the depwarns with
```yaml
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: no
```

but I can make them throw with 
```yaml
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: error
```
