### ISSUE TITLE
how to use coverage

### ISSUE THREAD

**Issue by maartenvd** [julia-actions/julia-runtest#6]
From the source code I gather that this action also allows coverage.io integration. What exactly should I add to my workflow file? I tried
```

      - uses: julia-actions/julia-runtest@latest
        with:
            codecov: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

which doesn't appear to do anything.
